/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Demo: typeof import('./docs/components/Demo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheLink: typeof import('./docs/components/TheLink.vue')['default']
    TheTheme: typeof import('./docs/components/TheTheme.vue')['default']
    XBulletinBoard: typeof import('@/components')['XBulletinBoard']
    XButton: typeof import('@/components')['XButton']
    XButtonSplit: typeof import('@/components')['XButtonSplit']
    XCaptchaSlider: typeof import('@/components')['XCaptchaSlider']
    XDatePicker: typeof import('@/components')['XDatePicker']
    XDateRangePicker: typeof import('@/components')['XDateRangePicker']
    XDialog: typeof import('@/components')['XDialog']
    XDrawer: typeof import('@/components')['XDrawer']
    XEmpty: typeof import('@/components')['XEmpty']
    XInput: typeof import('@/components')['XInput']
    XInputNumber: typeof import('@/components')['XInputNumber']
    XNativeSelect: typeof import('@/components')['XNativeSelect']
    XPagination: typeof import('@/components')['XPagination']
    XPopover: typeof import('@/components')['XPopover']
    XRadio: typeof import('@/components')['XRadio']
    XSegmented: typeof import('@/components')['XSegmented']
    XSelect: typeof import('@/components')['XSelect']
    XSelectItem: typeof import('@/components')['XSelectItem']
    XSimplePagination: typeof import('@/components')['XSimplePagination']
    XSwitch: typeof import('@/components')['XSwitch']
    XTable: typeof import('@/components')['XTable']
    XTag: typeof import('@/components')['XTag']
    XTextarea: typeof import('@/components')['XTextarea']
  }
}
